version: '3'
services:
  app:
    image: erikasignal/url-shortener-service:v3
    #build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"